//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationOutage
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearlyAvailability
    {
        public int Id { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public int Availability { get; set; }
    }
}
